### ISSUE TITLE
Valkyrie Source Code  workspace file download issue

### ISSUE THREAD

**Issue by teaminline303** [NASA-JSC-Robotics/valkyrie#13]
curl -u $GITHUB_USER -H "Accept: application/vnd.github.raw" "https://api.github.com/repos/NASA-JSC-Robotics/val_workspaces/contents/public_https_full_workspace.yaml?ref=develop" > workspace.yaml
I get the following
 {
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}

Could there be any permission issues

**Comment by jlack1987** [comment]
@kodyensley can we confirm whether or not @teaminline303 has been given access?

**Comment by jlack1987** [comment]
@teaminline303 yeah it looks like you don't have access to the repo's. Which SRC group are you a part of?

**Comment by teaminline303** [comment]
I am working with Rob Platt at Northeastern Univ.
