### ISSUE TITLE
uoe: control crashes when executing arm reaching plans

### ISSUE THREAD

**Issue by mauricefallon** [NASA-JSC-Robotics/valkyrie#16]
Reposting this issue here:
https://github.com/ihmcrobotics/ihmc-open-robotics-software/issues/17

**Comment by jlack1987** [comment]
@iamwolf what's the status of this issue?

**Comment by iamwolf** [comment]
Resolved as of today. Thanks for checking in and apologies for not closing
it earlier along with the other issue.

**Comment by jlack1987** [comment]
No worries, glad it got taken care of!
