### ISSUE TITLE
Right lower arm joints have reversed axes

### ISSUE THREAD

**Issue by wxmerkt** [NASA-JSC-Robotics/valkyrie#22]
As reported on Slack, the joints of the right lower arm have their rotation axes reversed, cf.

[![Video](http://img.youtube.com/vi/3HM3RhL0dJ0/0.jpg)](http://www.youtube.com/watch?v=3HM3RhL0dJ0)
https://www.youtube.com/watch?v=3HM3RhL0dJ0

We've so far seen this for:
- all pitch joints
- forearm yaw

**Comment by MathisFrankB** [comment]
We have pushed a change to val description that should correct this issue.

**Comment by wxmerkt** [comment]
I've just pulled from val_description, nuked build, devel, install and re-run catkin_make. Then compared the resulting URDF to the one we previously had with meld. Did not see any change apart from the midfoot_rear collision groups being added, although I am seeing your modifications. Re-run a log on the new URDF and the visualisation problem did not go away. 

Note, the resulting URDF is no different from the previous despite the changes.

**Comment by jlack1987** [comment]
It's not an URDF change Wolf it's a change in the underlying finger transmissions I think, right @MathisFrankB ?

**Comment by MathisFrankB** [comment]
Yes and no. The change is in the transmission for the finger joints, but the change should appear in the transmission section of the urdf. I will take a look at this Monday.

**Comment by MathisFrankB** [comment]
@wxmerkt please open the following file: src/val_description/model/robots/forearm_right.xacro and see if the forearm yaw transmission reads like

<xacro:simple_forearm_position_transmission jointName="${ForearmYawActuatorName}" actuatorName="${ForearmYawActuatorName}" nodeName="${ForearmYawNode}" actuatorApi="${ForearmYawApi}" reflect="${reflect}"/>

**Comment by MathisFrankB** [comment]
xacro:simple_forearm_position_transmission jointName="${ForearmYawActuatorName}" actuatorName="${ForearmYawActuatorName}" nodeName="${ForearmYawNode}" actuatorApi="${ForearmYawApi}" reflect="${reflect}"

**Comment by jlack1987** [comment]
@wxmerkt what's the status here? Has this been resolved on your end?

**Comment by wxmerkt** [comment]
With the robot down for a week and busy diagnosing, I didn't get a chance to test and check it yet. Will put it on the list for tomorrow (it's below getting the robot functional and available for other users though). I'll be in touch.

**Comment by jlack1987** [comment]
Yeah no worries. I understand it's low priority. Just let us know whenever you get a chance. Thanks!

**Comment by wxmerkt** [comment]
Fixed, thanks guys!
