### ISSUE TITLE
URDF with stubs?

### ISSUE THREAD

**Issue by mauricefallon** [NASA-JSC-Robotics/valkyrie#23]
We see that val_description has "no hand" versions. Do these hand have stubs or do they terminate just below the elbows?

I'd like to be able to create URDFs with the stubs accurately rendered: for collision free planning and for balancing using the arms (in future)

**Comment by MathisFrankB** [comment]
The no hands urdf stops at the j5 joint (which is the base of the forearm). We currently do not have a urdf with the forearm mass sims in them.

**Comment by jlack1987** [comment]
I have been thinking about getting rid of the "no hands" urdf's completely and replacing it with a model that has the mass sims. Shouldn't be difficult to do.

**Comment by mauricefallon** [comment]
Ok, BTW we don't use the no hands version. The models with mass sims would be useful

**Comment by jlack1987** [comment]
This one is on the way. I hope you like dense, monochrome meshes :)

**Comment by jlack1987** [comment]
![screenshot from 2016-05-12 17 16 07](https://cloud.githubusercontent.com/assets/6334699/15232233/7d28d916-1865-11e6-96d2-112709ed570d.png)

alright @mauricefallon this one is ready to go. Pull everything and do a clean build and you should have some URDF's with the mass sims.

**Comment by mauricefallon** [comment]
Thanks. Are you referring to the develop branch:
https://github.com/NASA-JSC-Robotics/val_description/tree/develop/model/meshes/arms

FYI: @MarcoCar @yimingyanged

**Comment by jlack1987** [comment]
Yep that's the one
