### ISSUE TITLE
Can't install visualizer

### ISSUE THREAD

**Issue by tkoolen** [NASA-JSC-Robotics/valkyrie#31]
While following [this guide](https://github.com/NASA-JSC-Robotics/valkyrie/wiki/Get-Valkyrie-Code), I tried installing the "MIT Vis02" visualizer, but I got this:

![image](https://cloud.githubusercontent.com/assets/2585880/14955591/98219848-1040-11e6-9d9a-d976b875bb8c.png)

Any ideas?

**Comment by jlack1987** [comment]
You tried installing this on your personal computer or what? The 'MIT Vis02' is specifically for your visualizer computer that's running the robot and is already installed. Also there is an actual link on that page for the debian 'MIT Vis02' that you want. Unfortunately we are not allowed to make our debs public, so we aren't able to make it all sudo apt-getable.

**Comment by tkoolen** [comment]
> You tried installing this on your personal computer or what?

Yup, I'm just a robot following instructions to the letter and this looked like it needed to be done ;-)

**Comment by jlack1987** [comment]
Did you download the debian [here](https://github.com/NASA-JSC-Robotics/valkyrie/wiki/Setup-Valkyrie-Developer-Environment). It's the debian under the 'Generic System Config' link

**Comment by tkoolen** [comment]
Yeah, I downloaded the generic system config one. I really just followed instructions word for word. I closed the issue because clearly I wasn't supposed to do the MIT vis step anyway.

**Comment by jlack1987** [comment]
Ok I think  I see the issue. It's not so clear that unless your installing a visualizer computer, you don't need to continue after checking out our code. I have put a clarifying statement in the wiki that will hopefully prevent others from making the same mistake.
