### ISSUE TITLE
Ankle roll torques are communicated to IHMC controller.

### ISSUE THREAD

**Issue by SylvainBertrand** [NASA-JSC-Robotics/valkyrie#5]

**Comment by jlack1987** [comment]
We already fixed this and send you the updated debians in an email this morning. Follow the instructions in the email to install them.

**Comment by SylvainBertrand** [comment]
Alright I’ll close the ticket next time I run Val. Do you know how to add a “Review” column in the zenhub board (like in Jira)?

**Comment by kodyensley** [comment]
I can add/modify the board. What would you like to add/remove or rename?
-Kody

--

Kody Ensley
B:32A R:2009
Robotic Systems Technology Branch, ER4
NASA/Johnson Space Center
Houston, Texas 77058
Ph: 406-270-0714

**Comment by SylvainBertrand** [comment]
Yo!


Sorry, I just saw your email. I like the current setup, thanks!


Sylvain
