### ISSUE TITLE
IMU and FT sensor wiki pages are pointing to the wrong datasheets

### ISSUE THREAD

**Issue by traversaro** [NASA-JSC-Robotics/valkyrie#8]
FT wiki page is pointing to IMU datasheet: https://github.com/NASA-JSC-Robotics/valkyrie/wiki/ATI-Sensors .
IMU wiki page is pointing to FT datasheet: https://github.com/NASA-JSC-Robotics/valkyrie/wiki/IMU-Sensors .

**Comment by kodyensley** [comment]
Thank you kind stranger. Links swapped.
