### ISSUE TITLE
shared_memory_transport_sliderboard doesn't get cloned when cloning a workspace from the workspace files

### ISSUE THREAD

**Issue by jlack1987** [NASA-JSC-Robotics/valkyrie#9]
Recreating this ticket from @scpeters , trying to clone a workspace from public_full_workspace.yaml gives following error:

=== ./shared_memory_transport_sliderboard (git) ===
Could not clone repository 'git@github.com:NASA-JSC-Robotics/shared_memory_transport_sliderboard.git': Cloning into '.'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by pstrawse** [comment]
There was a permissions issue.  The permissions for this repo has been updated and this issue should be fixed.

**Comment by jlack1987** [comment]
Tested just now and can confirm the sliderboard is clone successfully.
